### PR TITLE
Updating to version 0.6.0

### PR DESCRIPTION
**Pull request by lawsonAGMT**
I'm trying to upgrade the package to v0.6.0 re: [this](https://github.com/IfcOpenShell/IfcOpenShell/issues/809) issue.

I'm not 100% sure that this is what needs to be changed since I've never worked with a conda package before. Let me know if there is anything else that needs to be change.

### CODE REVIEW

**Comment by lawsonAGMT** [comment]
Not sure I totally understand the build failures, but it looks like it is only happening for python version <= 3.7

@aothms is 3.8 the only supported version now? Or is something funky going on?

**Comment by looooo** [comment]
@conda-forge-admin, please rerender

**Comment by looooo** [comment]
I have no idea. There is really py3.8 pulled at build-time for the py3.7 package. Let's see if rerendering helps.

**Comment by lawsonAGMT** [comment]
I believe I've ruled out any change in this repo being responsible for the problem. But, the only change in IfcOpenShell that mentions python 3.8 in any way seems to be [this](https://github.com/IfcOpenShell/IfcOpenShell/commit/3c355b4848e939fdb3da7872a1bcbb60d76ef11b) one.

I've modified my pull request temporarily to reference a version of v0.6.0 without that change just to see if it helps any.

Otherwise, I think I've reached the extent of what I can do with my familiarity level at this time.

**Comment by looooo** [comment]
I don't know why python is pulled into the build-env. This shouldn't happen.

**Comment by lawsonAGMT** [comment]
Undoing change to 0.6.0 to see if maybe something external changed since the last build was run 21 days ago.

Unfortunately I don't have any more time to commit to debugging this at this point, and will resort to downloading the package from the ifcopenshell site.

Good luck to anyone else who can try and figure this out.

**Comment by lawsonAGMT** [comment]
looks like it's working, thanks!!

**Comment by lawsonAGMT** [comment]
@looooo would it be possible to merge this now?

**Pull request merged**
