### PR TITLE
Fixing the sha256

### PR DESCRIPTION
**Pull request by lawsonAGMT**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [no - fixing first build?] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Apologies, I seem to have added the incorrect sha256 in my last pull request.

### CODE REVIEW

**Comment by lawsonAGMT** [comment]
@conda-forge-admin, please rerender

**Comment by looooo** [comment]
was the release updated? Or why did the sha256sum change?

**Comment by lawsonAGMT** [comment]
That's a good question. It does look like there are new commits on the 0.6.0 branch. @aothms is 0.6.0 still under development?

**Comment by aothms** [comment]
> @aothms is 0.6.0 still under development?

yes, but no major breaking changes anymore, as I said, I don't mind tagging another beta version if that helps you guys

**Comment by looooo** [comment]
So 0.6.0 is expected to change? Normally small fixes are added by increasing the last number of the version (0.6.1). This would help a lot, as a PR is done by a bot for every release, but not if the source of an existing release changes.

**Comment by aothms** [comment]
v0.6.0 is the branch in IfcOpenShell, and we have releases like v0.6.0b0 https://github.com/IfcOpenShell/IfcOpenShell/releases/tag/v0.6.0b0 which iirc is what is currently on conda-forge. 

To summarize we're working towards a 0.6.0 release by various beta releases and b0 is now on conda-forge.

Does it help if I tag v0.6.0b1 or does that not map nicely to conda version numbers?

**Comment by looooo** [comment]
I guess it's too late as we went for 0.6.0 already. I can move the current 0.6.0 to broken and use a beta release once it's available.

**Comment by lawsonAGMT** [comment]
There are some fixes in the current version of 0.6.0 that are critical to our project, which is why I started this PR. Something like 0.6.0b1 at least would be very helpful.

**Pull request merged**
